### ISSUE TITLE
panic during `icm.initialize(Delay).await.unwrap()`

### ISSUE THREAD

**Issue by listentodella** [ProfFan/icm426xx#1]
If embedded_hal_bus::spi used diectly, SPI read chipid succesfully, which means the hardware is OK.
But if icm.initialize called, it will panic at SPI transfer:

![image](https://github.com/user-attachments/assets/5df9b3a2-aa86-468e-8857-919fe0c89b82)

**Comment by ProfFan** [comment]
Please include your stack trace, thanks.

**Comment by listentodella** [comment]
![image](https://github.com/user-attachments/assets/2a3bca9e-1b2c-432c-bc75-d2d39c6ee6a2)
I tested it on the STM32F469.

**Comment by ProfFan** [comment]
This seems to be a problem with your SPI driver, most likely a SPI configuration error.

**Comment by listentodella** [comment]
![image](https://github.com/user-attachments/assets/e2861344-f910-4295-96f7-5d18482562cc)
If I use the commented code instead of icm api, I can read the chip id. So I think the SPI configuration is correct.

**Comment by ProfFan** [comment]
Did you try without DMA? DMA has certain alignment requirements that may have not been considered in generic drivers.

**Comment by listentodella** [comment]
yeah, without dma, icm can  initialize successfully. 

I only vrified with blocking mode.

**Comment by ProfFan** [comment]
Then this is a problem with the embassy-stm32 DMA driver. You may need to open an issue there.
